// Generated by CoffeeScript 1.3.3
(function() {
  var config;

  config = {
    base: './',
    debug: true
  };

  seajs.config(config);

  define(function(require) {
    console.log('seajs start');
    return require('app/app.js');
  });

}).call(this);
